"""
Dynamical Lie Algebra (DLA) Dimension Analyzer for Quantum Neural Networks.

Computes the Lie closure g = Lie({i G_k}) through iterative nested commutators
and singular value decomposition to prove polynomial vs. exponential Lie algebra dimension.
"""

from __future__ import annotations
import numpy as np
from typing import List, Tuple, Dict, Any


def compute_commutator(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    """Computes Lie bracket [A, B] = AB - BA."""
    return a @ b - b @ a


def orthonormalize_basis(basis: List[np.ndarray], tol: float = 1e-7) -> List[np.ndarray]:
    """Orthonormalizes a set of anti-Hermitian matrix generators under Hilbert-Schmidt inner product."""
    if not basis:
        return []

    ortho = []
    for mat in basis:
        curr = mat.copy()
        for b in ortho:
            proj = np.real(np.trace(b.conj().T @ curr))
            curr -= proj * b

        norm = np.sqrt(np.real(np.trace(curr.conj().T @ curr)))
        if norm > tol:
            ortho.append(curr / norm)

    return ortho


class DynamicalLieAlgebraAnalyzer:
    """
    Analyzes the Dynamical Lie Algebra (DLA) generated by a set of parameterized gates.
    """

    def __init__(self, generators: List[np.ndarray], max_iterations: int = 5, tol: float = 1e-7):
        # Convert generators to anti-Hermitian basis: i * G
        self.raw_generators = [1.0j * g.astype(np.complex128) for g in generators]
        self.max_iter = max_iterations
        self.tol = tol

    def compute_dla_dimension(self) -> Dict[str, Any]:
        """
        Iteratively computes nested commutators until the Lie algebra basis closes.
        """
        basis = orthonormalize_basis(self.raw_generators, self.tol)
        iter_counts = [len(basis)]

        for it in range(self.max_iter):
            new_elements = []
            n_current = len(basis)

            for i in range(n_current):
                for j in range(i + 1, n_current):
                    comm = compute_commutator(basis[i], basis[j])
                    norm = np.sqrt(np.real(np.trace(comm.conj().T @ comm)))
                    if norm > self.tol:
                        new_elements.append(comm)

            if not new_elements:
                break

            extended_basis = orthonormalize_basis(basis + new_elements, self.tol)
            iter_counts.append(len(extended_basis))

            if len(extended_basis) == len(basis):
                # Lie algebra is closed
                break

            basis = extended_basis

        dla_dim = len(basis)
        n_qubits = int(np.log2(basis[0].shape[0])) if basis else 0
        full_su_dim = 4**n_qubits - 1

        is_sub_exponential = dla_dim < (full_su_dim * 0.8)

        return {
            "dla_dimension": dla_dim,
            "full_su_dimension": full_su_dim,
            "is_sub_exponential": is_sub_exponential,
            "iteration_dimensions": iter_counts,
            "n_qubits": n_qubits,
        }
